### ISSUE TITLE
Modify Navbar section

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#10]
# Feature Request
Modify the navbar section and add the required links (home, projects, team, contribute, contact). Also replace the bulma logo image with elevate-lab logo.

**Comment by 2802harsh** [comment]
I would like to work on this

**Comment by Tlazypanda** [comment]
@2802harsh please go ahead :tada:

**Comment by kashc11** [comment]
Hi! I'd like to work on this too!

**Comment by rush-tea** [comment]
> # Feature Request
> Modify the navbar section and add the required links (home, projects, team, contribute, contact). Also replace the bulma logo image with elevate-lab logo.

A

> I would like to work on this

Navbar toggler is not working. You can look for that also.

**Comment by 2802harsh** [comment]
@rush-tea Yeah, I have noted that. Working on it.

**Comment by Tlazypanda** [comment]
@rush-tea @2802harsh Good team work 🤜  🤛

**Comment by 2802harsh** [comment]
@Tlazypanda ma'am Please review the PR [here](https://github.com/Elevate-Lab/elevate-lab-website/pull/22)
