### ISSUE TITLE
Design Event section and cards

### ISSUE THREAD

**Issue by garvitchittora** [Elevate-Lab/elevate-lab-website#102]
# Feature Request

### Describe your problem

Design the event section and cards. The event section should have the heading "Event".

**Comment by garvitchittora** [comment]
I will work on it :)

**Comment by garvitchittora** [comment]
@Tlazypanda ma'am this will work??

![Elevate-Lab-Website (3)](https://user-images.githubusercontent.com/54021348/95671394-366c0600-0bb4-11eb-9e80-5d1f6ff43f13.png)

**Comment by Tlazypanda** [comment]
Hey @garvitchittora can you please explain how the past events section will stack up when we have more entries I am not sure I completely follow :sweat_smile:

**Comment by garvitchittora** [comment]
@Tlazypanda 😅

![Desktop - 1 (1)](https://user-images.githubusercontent.com/54021348/95673054-024c1180-0bc3-11eb-9828-41ef2f3dceb5.png)

**Comment by garvitchittora** [comment]
@Tlazypanda ma'am this is fine?

**Comment by deepakDOTexe** [comment]
@garvitchittora lgtm except the EVENTS rgb colouring . Please change it.
