### ISSUE TITLE
Add landing page section 

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#11]
# Feature Request

### Describe your problem
Add a landing page section with a flat design illustration and some content about Elevate Lab.

**Comment by garvitchittora** [comment]
@Tlazypanda ma'am don't you think we should first make the design of the website complete then we should start the coding part?

**Comment by Tlazypanda** [comment]
Hey @garvitchittora we may do that but if we are letting the contributors develop it completely it might not be possible to make a design pattern that will be closely followed by contributors :sweat_smile:

**Comment by garvitchittora** [comment]
@Tlazypanda ok ma'am then can I work on it :D.

**Comment by Tlazypanda** [comment]
@garvitchittora  yesss!! 💯

**Comment by Elemento24** [comment]
Do we have to think of a design and Implement it, or is there a pre-defined design which we have to code up?

**Comment by rebekris** [comment]
Hi, @Elemento24 @Tlazypanda I can help with an interface design, if you allow me :smiley:
