### ISSUE TITLE
Remove the color styling (red yellow and green in text) in home page 

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#110]
# Feature Request

### Describe your problem
Currently the website home page has a some words with the red,yellow and green text which represents a google color scheme which is not relevant to Elevate Lab and can be removed.
https://elevate-lab.github.io/elevate-lab-website/index.html

**Comment by atmanad** [comment]
Hey! Tlazypanda I want to work on this.
