### ISSUE TITLE
Remove the color styling (red yellow and green in text) in team page

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#111]
# Feature Request

### Describe your problem
Currently the website team page has some words with the red,yellow and green text which represents a google color scheme which is not relevant to Elevate Lab and can be removed. 
https://elevate-lab.github.io/elevate-lab-website/assets/html/team.html

**Comment by Shreesh90** [comment]
@Tlazypanda Yes mam working on it :)

**Comment by Shreesh90** [comment]
@Tlazypanda Is this color for the text okay?
![Screenshot 2020-10-11 132204](https://user-images.githubusercontent.com/6941016/95673239-91a5f480-0bc4-11eb-81ed-aa926fab7d09.jpg)
