### ISSUE TITLE
Add about us section in footer

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#112]
# Feature Request

### Describe your problem
Currently the footer only has social links but adding a small about us section in the footer can improve the site.

**Comment by Priyansh-09** [comment]
Is this fine @Tlazypanda ?? 

![Screenshot 2020-10-11 133508](https://user-images.githubusercontent.com/55129015/95673534-e480ab80-0bc6-11eb-877f-491f444be352.png)

If yes, merge my earlier pull request #109 , I have pushed these changes also in that PR.

**Comment by Priyansh-09** [comment]
Can I do this again ?
This issue is still assigned to me.

**Comment by deepakDOTexe** [comment]
Yeah go on

**Comment by kartikagarwal9** [comment]
Can you assign me , i can contribute to it @deepakDOTexe

**Comment by deepakDOTexe** [comment]
@kartikagarwal9 Sorry but it is already assigned to @Priyansh-09 . Check back later or claim other open issues.

**Comment by kartikagarwal9** [comment]
Ok Thanks @deepakDOTexe
