### ISSUE TITLE
Toggle the site from dark to light theme (Part 1) Home Page

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#113]
# Feature Request

### Describe your problem
Create a light themed equivalent of the current home page by creating the css rules for light theme.
Refer this: -  https://gosink.in/javascript-css-toggle-dark-light-theme-based-on-your-users-preferred-scheme/

**Comment by 2802harsh** [comment]
@Tlazypanda ma'am should I include a dark mode toggle also?? Or just let the webpage detect user preference as described in the resource.

**Comment by Tlazypanda** [comment]
A toggle would be great!

**Comment by 2802harsh** [comment]
@Tlazypanda ma'am pls review the PR
