### ISSUE TITLE
Toggle the site from dark to light theme (Part 1) Team Page

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#114]
# Feature Request

### Describe your problem

Create a light themed equivalent of the current team page by creating the css rules for light theme.
Refer this: - https://gosink.in/javascript-css-toggle-dark-light-theme-based-on-your-users-preferred-scheme/

**Comment by chetas411** [comment]
@Tlazypanda  Can I also try this if the issue is open for all ?
