### ISSUE TITLE
Toggle the site from dark to light theme (Part 1) Project Page 

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#115]
# Feature Request

### Describe your problem
Create a light themed equivalent of the current project page by creating the css rules for light theme.
Refer this: - https://gosink.in/javascript-css-toggle-dark-light-theme-based-on-your-users-preferred-scheme/

**Comment by Tlazypanda** [comment]
Assigned to @hardikbajaj

**Comment by abhishekraj272** [comment]
@Tlazypanda Can you assign this to me?

**Comment by hardikbajaj** [comment]
@abhishekraj272  I am working on it!
