### ISSUE TITLE
Remove the color styling (red yellow and green in text) in project page

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#116]
# Feature Request

### Describe your problem
Currently the website project page has some words with the red,yellow and green text which represents a google color scheme which is not relevant to Elevate Lab and can be removed.
https://elevate-lab.github.io/elevate-lab-website/assets/html/project.html

**Comment by Shreesh90** [comment]
@Tlazypanda Can I take this issue?

**Comment by IC1101Virgo** [comment]
@Tlazypanda Ok ma'am ! working on it 😸

**Comment by fawad60** [comment]
can I create PR?
