### ISSUE TITLE
Fetch project card data from json

### ISSUE THREAD

**Issue by garvitchittora** [Elevate-Lab/elevate-lab-website#117]
# Feature Request

### Describe your problem

Fetch project card data from the JSON file like team page.
[team page](https://elevate-lab.github.io/elevate-lab-website/assets/html/team.html)

**Comment by Thilagavathi1** [comment]
Hi @garvitchittora @Tlazypanda 
Shall i work on this issue?Could you assign this issue to me?

**Comment by garvitchittora** [comment]
@Thilagavathi1 sure, go ahead.

**Comment by Thilagavathi1** [comment]
Have raised my [PR](https://github.com/Elevate-Lab/elevate-lab-website/pull/137).Please check this and let me know.
