### ISSUE TITLE
Add docs on how to set up project

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#12]
# Feature Request

### Describe your problem
Add docs on how to fork, clone and start the project. You may also add docs on how to setup Gh pages link.

**Comment by uglyprincess** [comment]
Ma'am, may I work on this issue?

**Comment by Tlazypanda** [comment]
@uglyprincess yes go ahead 🎉

**Comment by uglyprincess** [comment]
PR sent! Please review the file and suggest any changes.

**Comment by Tlazypanda** [comment]
Closed via #15
