### ISSUE TITLE
Change the 'LAB' in the site name to sentence-case

### ISSUE THREAD

**Issue by Shreesh90** [Elevate-Lab/elevate-lab-website#122]
# Feature Request

### Describe your problem

The name of the site at top in team and project page should be 'Elevate Lab' (as visible in the home page) instead of 'Elevate LAB'.
Home page: https://elevate-lab.github.io/elevate-lab-website/
Team page: https://elevate-lab.github.io/elevate-lab-website/assets/html/team.html
Project page: https://elevate-lab.github.io/elevate-lab-website/assets/html/project.html

**Comment by Priyansh-09** [comment]
Already done that in my PR #109
