### ISSUE TITLE
Add favicon logo for website

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#13]
# Feature Request

### Describe your problem
Add elevate-lab logo as favicon for website.

**Comment by kashc11** [comment]
Hi! Can I contribute to this?

**Comment by garvitchittora** [comment]
@Tlazypanda can I work on this?

**Comment by hardikbajaj** [comment]
The new logo, that Himanshu created??

**Comment by Tlazypanda** [comment]
Hey @kashc11 please go ahead :tada: You can find the relevant files in images/logo subdir :sweat_smile:

**Comment by Tlazypanda** [comment]
Closed via #27
