### ISSUE TITLE
Background color property for certain elements not working properly

### ISSUE THREAD

**Issue by 2802harsh** [Elevate-Lab/elevate-lab-website#134]
# Bug Report 

### Issue Summary
background-color property is not working for some elements like project and team cards, and they always inherit the global bg color.

### Expected Behavior
Elements for which bg color property is explicitly mentioned should follow this mentioned value of the property.

### Observed Behavior
global bg color inherited

**Comment by uglyprincess** [comment]
@2802harsh please review 🙌🏻
