### ISSUE TITLE
Bug in contact us form UI

### ISSUE THREAD

**Issue by stygian-96** [Elevate-Lab/elevate-lab-website#150]
# Bug Report 

### Issue Summary

- Contact us form width shrinks too much when window resized to mobile view.
- Orientation of form is not proper
- Text color is not readable

### Expected Behavior

 
- Contact us should be responsive in a way it should have some minimum width.
- It should be properly aligned.

#### Form width issue
![image](https://user-images.githubusercontent.com/54054289/95795204-6c6dcf00-0d07-11eb-9894-17a0660860b0.png)

#### Form orientation issue
![image](https://user-images.githubusercontent.com/54054289/95795311-adfe7a00-0d07-11eb-8260-d1170c5c6cdd.png)

**Comment by rush-tea** [comment]
Can i work on this issue?

**Comment by geeks5551** [comment]
Hey @stygian-96  can i work on this issue?

**Comment by Shreesh90** [comment]
@stygian-96 Please can I work on this issue ??

**Comment by stygian-96** [comment]
Go ahead @rush-tea

**Comment by Shreesh90** [comment]
@stygian-96 sorry I didn't see that you already assigned it to @rush-tea and started working on it 😶😶
