### ISSUE TITLE
Make "meet the team" heading visible in mobile view

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#156]
# Feature Request

### Describe your problem
On navigating to mobile view, the meet the team text is not completely visible.

![image](https://user-images.githubusercontent.com/33183263/95837165-eb8df200-0d5d-11eb-8887-3286a6a0d12f.png)

**Comment by hardikbajaj** [comment]
@Tlazypanda Can I make the changes in that particular tag only using style? Or I necessarily have to do styling in css file.

**Comment by Elemento24** [comment]
Hey @hardikbajaj, @Tlazypanda  I am really sorry, I didn't know this thing had a separate issue. I thought it was quite similar to my issue, so I fixed it as well, alongside my Issue. I am really really sorry!

**Comment by hardikbajaj** [comment]
No problem. ; )

**Comment by hardikbajaj** [comment]
@Tlazypanda ma'am, close this issue please

**Comment by Tlazypanda** [comment]
Hey @Elemento24 can you create an issue for @hardikbajaj to take up? :tada:

**Comment by Elemento24** [comment]
Hey @Tlazypanda , sure, I will do that...
Can you please close this one, Mam!
