### ISSUE TITLE
Improve Style of Contact Us section

### ISSUE THREAD

**Issue by uglyprincess** [Elevate-Lab/elevate-lab-website#159]
# Feature Request

### Describe your problem

The Contact Us form on the home page could use some work. Currently it's not very appealing and there seem to be some redundant features.
![image](https://user-images.githubusercontent.com/57333555/95841702-4bd36280-0d63-11eb-8a90-072df1e73d7d.png)
As you can see, the form is neither left-aligned, nor right-aligned nor justified. It sits in this weird position on the left side of the screen. Moreover, the font color has poor visibility and the check marks seem to serve no function.

### Describe the solution you'd like

Align the form in either of the aforementioned manners (left-, right- or justified), improve the color of the headings and try to align all three text areas by giving them the same width. You only need to fiddle around with styles.css for this issue.

### Additional context
-

**Comment by geeks5551** [comment]
@uglyprincess  can i work on this?

**Comment by uglyprincess** [comment]
> @uglyprincess can i work on this?

sure @geeks5551, go ahead! 🎉

**Comment by geeks5551** [comment]
@deepakDOTexe  assign me with  this issue?

**Comment by rush-tea** [comment]
@uglyprincess similar kind of issue has already been opened pls check #150 ....

**Comment by uglyprincess** [comment]
Due to potential merge conflicts, I'm closing this issue for now.
