### ISSUE TITLE
Navbar Background Issue

### ISSUE THREAD

**Issue by 2802harsh** [Elevate-Lab/elevate-lab-website#163]
# Bug Report 

### The navbar background does not cover the whole width

The background color of the Navbar only spans across the width of the content and not the 100% page width. The issue is not quite visible in current background color. Change background color and you will notice the issue.

### Expected Behavior

The background color of Navbar should span the whole (100%) width of the page.

### Observed Behavior

See the screenshot below :
![Screenshot from 2020-10-13 17-48-55](https://user-images.githubusercontent.com/58396239/95859543-66660580-0d7c-11eb-8fa5-5d4864c305be.png)

### Steps to Reproduce

You probably need to remove the margin from Navbar ( padding can be used instead for that purpose )

**Comment by geeks5551** [comment]
@2802harsh can i work on this issue?

**Comment by 2802harsh** [comment]
@geeks5551 Yeah! go ahead

**Comment by geeks5551** [comment]
@tejma17 @Tlazypanda pls assign me this issue

**Comment by geeks5551** [comment]
okk i will do
