### ISSUE TITLE
Navbar Title not vertically aligned

### ISSUE THREAD

**Issue by 2802harsh** [Elevate-Lab/elevate-lab-website#164]
# Bug Report 

### Expected Behavior

The navbar title should be vertically in line with other navbar items

### Observed Behavior

See the screenshot below :
![Screenshot from 2020-10-13 17-53-23](https://user-images.githubusercontent.com/58396239/95860022-13d91900-0d7d-11eb-8c90-400d1ffcf63e.png)

**Comment by thelavenderhue** [comment]
@2802harsh can I work on this?

**Comment by tejma17** [comment]
@thelavenderhue go ahead :)
