### ISSUE TITLE
Add links to Event Page 

### ISSUE THREAD

**Issue by deepakDOTexe** [Elevate-Lab/elevate-lab-website#170]

**Comment by kumarmanish03** [comment]
I want to work on it

**Comment by deepakDOTexe** [comment]
@kumarmanish03 I have assigned you this issue.

**Comment by kumarmanish03** [comment]
@deepakDOTexe  Which links is to be added on Events page. Is it to make a sample page having having two tabs and event 1 event 2 etc.( like Project Page)

**Comment by deepakDOTexe** [comment]
@kumarmanish03 The nav bar menu item should take us to event page
