### ISSUE TITLE
Add space between description and Logo of Elevate-Lab

### ISSUE THREAD

**Issue by Elemento24** [Elevate-Lab/elevate-lab-website#176]
# Bug Report 

### Issue Summary
There is almost Negligible Space between the Icon and the description of Elevate Lab, in portrait tablet aspect ratio, and below that

### Expected Behavior
There should be a considerable about of margin between those.

### Screenshots (if any)
![Screenshot from 2020-10-14 16-42-16](https://user-images.githubusercontent.com/58396433/95983453-40ee0000-0e3f-11eb-84c7-15880dcf0d65.png)

**Comment by Elemento24** [comment]
Assigned to @hardikbajaj

**Comment by Ranveer251** [comment]
can I do this?

**Comment by Tlazypanda** [comment]
Hey @Ranveer251 can you take up #40 since this issue is assigned to @hardikbajaj 😅

**Comment by Ranveer251** [comment]
ok
