### ISSUE TITLE
Dark Mode Toggle Fails on root route

### ISSUE THREAD

**Issue by 2802harsh** [Elevate-Lab/elevate-lab-website#181]
# Bug Report 

### Issue Summary

The css files dark.css and light.css have different relative paths w.r.t index.html and other html pages. index.js takes care of this only for the route '/index.html'. But the home page is also rendered on root '/' route of gh pages, and thus dark mode toggle has no effect there.
### Expected Behavior

The toggle should also work for root route and render the respective css file from correct relative path w.r.t index.html

### Observed Behavior

Currently it is not working for root route.

### Steps to Reproduce
You need to add extra condition in index.js to take care of this.

### Screenshots (if any)
![Screenshot from 2020-10-14 21-59-39](https://user-images.githubusercontent.com/58396239/96018238-9ee30d80-0e68-11eb-839e-8d1267b91faf.png)
![Screenshot from 2020-10-14 21-59-27](https://user-images.githubusercontent.com/58396239/96018251-a2769480-0e68-11eb-8f1a-72ac0998f7c8.png)

**Comment by Ranveer251** [comment]
can i do this?

**Comment by 2802harsh** [comment]
@deepakDOTexe sir pls assign @Ranveer251 this issue

**Comment by Ranveer251** [comment]
@deepakDOTexe sir pls review my PR and suggest any changes if required.
