### ISSUE TITLE
Layout enhancement in Project page

### ISSUE THREAD

**Issue by deepakDOTexe** [Elevate-Lab/elevate-lab-website#186]
The project card rows have no padding between them. Fix this so that the rows are well seperated and cards don't overlap

![issue_new](https://user-images.githubusercontent.com/46655706/96120816-c095d080-0f0c-11eb-8fcf-8fa43de63bb5.png)

**Comment by BLACK-PEARLL** [comment]
i want to do it ,please assign me @deepakDOTexe

**Comment by pravdorin** [comment]
Is it possible to assign few people @BLACK-PEARLL ? I can make fix today.

**Comment by BLACK-PEARLL** [comment]
i done it @deepakDOTexe  and also made a pull request :)
