### ISSUE TITLE
Cards not rendered on team route for newer entries

### ISSUE THREAD

**Issue by Ranveer251** [Elevate-Lab/elevate-lab-website#200]
# Bug Report 
Even after adding the details in the assets/data/data.json file, the cards corresponding to them are not rendered on the team route.
### Issue Summary
 **To notice the issue first see assets/data/data.json and then go [here](https://elevate-lab.github.io/elevate-lab-website/assets/html/team.html). You can clearly see that for the last three contributors a card is not rendered.**

### Expected Behavior
A card should be rendered for each contributor/maintainer (in the data.json file) on the team route.
 
### Observed Behavior
Information Card is not rendered for each contributor on the team route.

### Screenshots (if any)
![image](https://user-images.githubusercontent.com/53096435/96254067-4f205580-0fd2-11eb-9084-ed261821f7b5.png)

![image](https://user-images.githubusercontent.com/53096435/96253977-28621f00-0fd2-11eb-861a-c19830d5cd40.png)

Please review the issue.
Please assign this to me.

**Comment by Ranveer251** [comment]
@Tlazypanda  can I want to work on this

**Comment by Tlazypanda** [comment]
Hey @Ranveer251 nice catch :+1:  go ahead :tada:
