### ISSUE TITLE
Dark Mode Toggle button hidden behind Nav Bar in mobile view

### ISSUE THREAD

**Issue by hardikbajaj** [Elevate-Lab/elevate-lab-website#207]
# Bug Report 

### Issue Summary

The Dark Mode toggle button is hidden behind the nav bar in the mobile view, also it is pushing the main content very much down.

### Observed Behavior
![WhatsApp Image 2020-10-16 at 20 05 22](https://user-images.githubusercontent.com/58038410/96272276-851e0380-0feb-11eb-9b5c-7b5e32cd67ba.jpeg)

**Comment by 2802harsh** [comment]
I want to work on this.

**Comment by BLACK-PEARLL** [comment]
i want to work on this
please assign

**Comment by achalesh27022003** [comment]
Can I work on this please?

**Comment by IC1101Virgo** [comment]
Assigned to @2802harsh
