### ISSUE TITLE
"Mixed Content" error in chrome related to Google Fonts

### ISSUE THREAD

**Issue by chuckyroh** [Elevate-Lab/elevate-lab-website#211]
# Bug Report 

### Issue Summary

On Chrome, there is a "Mixed Content" error in the console when loading any page. Issue is that the page is served through https but the google font is served through http

### Expected Behavior

I expected no errors in Chrome.

### Observed Behavior

I observed that in the Chrome Dev console there was an error. Fonts not loaded on the page.

### Steps to Reproduce

1. Open page (in Chrome)
2. View console for message
3. Font "Poppins" and "Racing Sans One" not loaded

### Screenshots (if any)

![Chrome Error](https://user-images.githubusercontent.com/12401186/96328002-6f144100-0ff3-11eb-98da-db7939571c2f.png)

**Comment by chuckyroh** [comment]
Fix coming soon

**Comment by kundanb** [comment]
I want to work on this issue.
