### ISSUE TITLE
CSS in Navbar on hover shifts unnaturally

### ISSUE THREAD

**Issue by chuckyroh** [Elevate-Lab/elevate-lab-website#213]
# Bug Report 

### Issue Summary

When hovering on items in navbar, the element seems to shrink and pull up the underline and also the width goes a little short and longer.

### Expected Behavior

I expected only the background rectangle to appear without the underline, and without shifting the width.

### Observed Behavior

I observed that the active underline shifts up a little. And the width shifts smaller and longer, which pushes the sibling elements.

### Steps to Reproduce

1. Hover on navbar items
2. Observe the transition

### Screenshots (if any)

![Navbar Style Error](https://user-images.githubusercontent.com/12401186/96328439-e77d0100-0ff7-11eb-9f3a-e4069cfe0742.gif)

**Comment by chuckyroh** [comment]
Observed on Chrome browser

**Comment by kundanb** [comment]
I can fix it.

**Comment by IC1101Virgo** [comment]
Assigned to @kundanb
