### ISSUE TITLE
Change Hover Effect in Light Mode

### ISSUE THREAD

**Issue by Priyansh-09** [Elevate-Lab/elevate-lab-website#230]
# Bug Report 

### Issue Summary

Currently in Light mode, hover effect of nav-links doesn't look good. Fix this issue.

### Screenshots (if any)

![WhatsApp Image 2020-10-21 at 21 11 39](https://user-images.githubusercontent.com/55129015/96744036-3ce35480-13e2-11eb-98bc-18618e7d1932.jpeg)

**Comment by Priyansh-09** [comment]
@Tlazypanda @tejma17 @deepakDOTexe I want to work on this.

**Comment by tejma17** [comment]
@Priyansh-09 you can work on this 👍
