### ISSUE TITLE
Fix The Toggle Button Position In Hamburger View

### ISSUE THREAD

**Issue by geeks5551** [Elevate-Lab/elevate-lab-website#234]
# Bug Report 

### Issue Summary

-As we can see from the screenshots attached in the issue section in the hamburger view(both in mobile or tab modes) the position of the Toggle Button Is Fluctuating. Fix its position at the top(i.e on the navbar beside the hamburger icon) as shown in the bottommost screenshot
 

### Screenshots of the issue

![Screenshot (3133)](https://user-images.githubusercontent.com/58395557/96801194-b1d77e00-1424-11eb-95a6-cab914ffa126.png)
![Screenshot (3134)](https://user-images.githubusercontent.com/58395557/96801207-bac84f80-1424-11eb-9b7f-d88d308bd72e.png)

###Screenshot of the final result(pic taken from other website to show result as example):-
![Screenshot (3130)](https://user-images.githubusercontent.com/58395557/96801279-da5f7800-1424-11eb-9025-e99c013f9e69.png)

**Comment by geeks5551** [comment]
@deepakDOTexe @tejma17 @Tlazypanda
 Can i work on this issue?

**Comment by kumaraditya2002** [comment]
cam i work on this issue??

**Comment by tejma17** [comment]
@geeks5551 for this we have to remove the title from navbar. 😅 I think the current position is good.

**Comment by geeks5551** [comment]
@tejma17 no sir , we can shift the toggle button to the navbar in the hamburger view  without the message(i.e light and the dark mode which is clearly understood and can be omitted for hamburger view) then it will be adjusted comfortably in the navbar,

**Comment by tejma17** [comment]
Alright @geeks5551 go ahead 👍
