### ISSUE TITLE
Add The Toggle Button In The Event Page

### ISSUE THREAD

**Issue by geeks5551** [Elevate-Lab/elevate-lab-website#235]
# Feature Request

### Describe your problem
-As we can see from the screenshot there is no toggle button in the event page . Add it In the event Page

### Screenshots(if any)
![Screenshot (3136)](https://user-images.githubusercontent.com/58395557/96802147-ddf3fe80-1426-11eb-829f-c7afb0d9a30b.png)

**Comment by geeks5551** [comment]
@tejma17 @deepakDOTexe @Tlazypanda 
Can i work on this issue?

**Comment by BLACK-PEARLL** [comment]
can i work on this?
@deepakDOTexe @tejma17 @Tlazypanda

**Comment by tejma17** [comment]
@geeks5551 go ahead
