### ISSUE TITLE
Dark Mode Toggle not working for Contact Section

### ISSUE THREAD

**Issue by kumarmanish03** [Elevate-Lab/elevate-lab-website#238]
# Bug Report 

### Issue Summary

    Dark Mode Toggle Button not working if we go to Contact Section (On clicking 'Contact' Navbar). You may go through the ss attached

### Expected Behaviour
 
Page should remain in Mode(dark/light) even after clicking Contact Navbar Link

### Screenshots (if any)

![Screenshot from 2020-10-22 20-17-03](https://user-images.githubusercontent.com/41566808/96888894-b5f6b080-14a3-11eb-94e3-ef199cda5168.png)

**Comment by kumarmanish03** [comment]
I want to fix this Bug

**Comment by IC1101Virgo** [comment]
Can I work on this?

**Comment by IC1101Virgo** [comment]
@kumarmanish03 You have been assigned one of the issues :)
