### ISSUE TITLE
Add Footer for Events Page

### ISSUE THREAD

**Issue by kumarmanish03** [Elevate-Lab/elevate-lab-website#239]
# Feature Request

### Add a footer for the Events page

Footer must be the same as used in other pages of the site

![Screenshot from 2020-10-22 23-44-43](https://user-images.githubusercontent.com/41566808/96912986-b0f42a00-14c0-11eb-8920-0c1dfa9924c9.png)

**Comment by kumarmanish03** [comment]
I want to work on this

**Comment by IC1101Virgo** [comment]
Assigned to @kumarmanish03

**Comment by IC1101Virgo** [comment]
Closing this issue as PR to this issue has been merged. 😄
