### ISSUE TITLE
Event page not light-mode frinedly

### ISSUE THREAD

**Issue by hardikbajaj** [Elevate-Lab/elevate-lab-website#240]
# Bug Report 

### Issue Summary

The contents of the light mode on the event page are not visible. So change the CSS of that page and try not to add the toggle functionality on that page for now as a different issue will be opened for that.
### Screenshots 

![Screenshot from 2020-10-22 22-33-14](https://user-images.githubusercontent.com/58038410/96906212-222edf80-14b7-11eb-810e-fa1a60269663.png)

### Expected Behavior

 
I expected contents would be visible

### Observed Behavior

I observed that contents are not visible.

### Steps to Reproduce

1. Go to light.css file.
2. Do the required changes
3. Test it by changing the mode on the home page and then move to the events page.

**Comment by BLACK-PEARLL** [comment]
can i?

**Comment by hardikbajaj** [comment]
Yes, @BLACK-PEARLL go ahead...
