### ISSUE TITLE
"Home" Page and "Contact Us" Page Shows Same Contents

### ISSUE THREAD

**Issue by kmlhsn** [Elevate-Lab/elevate-lab-website#246]
# Bug Report 

### Issue Summary

"Home" and "Contact Us" shows same contents on the page.

### Expected Behavior

"Home" and "Contact Us" page should have different contents
 

### Observed Behavior

"Home" and "Contact Us" shows same contents on the page.

### Steps to Reproduce

1. Go to https://elevate-lab.github.io/elevate-lab-website/index.html
2. Click on "Home" and "Contact Us"

**Comment by hardikbajaj** [comment]
I think the page shifts to the **Contact us** section of Home page when we click on it. So that's not an issue
