### ISSUE TITLE
"Events","Contribute","Learn" and "Contact Us" are not active when they are clicked

### ISSUE THREAD

**Issue by kmlhsn** [Elevate-Lab/elevate-lab-website#247]
# Bug Report 

### Issue Summary

"Events","Contribute","Learn" and "Contact Us" menu items are not active when they are clicked

### Expected Behavior
"Events","Contribute","Learn" and "Contact Us" should be active when they are clicked

### Observed Behavior

"Events","Contribute","Learn" and "Contact Us" menu items are not active when they are clicked
### Steps to Reproduce

1. Go to https://elevate-lab.github.io/elevate-lab-website/index.html
2. Click on "Events","Contribute","Learn" and "Contact Us" menu items 

### Screenshots (if any)

![image](https://user-images.githubusercontent.com/32615215/97083225-6abdd880-1630-11eb-86df-67d6562655f0.png)

**Comment by hardikbajaj** [comment]
Can I work on this?
