### ISSUE TITLE
Follow us links should have respective links

### ISSUE THREAD

**Issue by kmlhsn** [Elevate-Lab/elevate-lab-website#248]
# Bug Report 

### Issue Summary
Follow us links--"Instagram","LinkedIn","twitter","Facebook","GitHub","YouTube" do not have respective links

### Expected Behavior

Follow us links--"Instagram","LinkedIn","twitter","Facebook","GitHub","YouTube" should have respective links

### Observed Behavior
Follow us links--"Instagram","LinkedIn","twitter","Facebook","GitHub","YouTube" do not have respective links

### Steps to Reproduce
1. Go to https://elevate-lab.github.io/elevate-lab-website/index.html
2. Scroll down to bottom

### Screenshots (if any)
![image](https://user-images.githubusercontent.com/32615215/97083451-ff750600-1631-11eb-846d-3c04aa10132f.png)

**Comment by BLACK-PEARLL** [comment]
can i?

**Comment by BLACK-PEARLL** [comment]
can i?

**Comment by tejma17** [comment]
Elevate lab doesn't have any social media handles right now.
