### ISSUE TITLE
Design team section and cards

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#26]
# Feature Request

### Describe your problem
Design the team section and cards. The team section should have a heading "Team" followed by the card. For now, you may create a single card. Also don't forget to link the Team section to the navbar Team link.

**Comment by garvitchittora** [comment]
@Tlazypanda can I do this? :P

**Comment by Tlazypanda** [comment]
@garvitchittora Go ahead :tada:  also looping in @stygian-96

**Comment by garvitchittora** [comment]
@stygian-96 @Tlazypanda plz review 😨
