### ISSUE TITLE
Design framework: Set up a simple boilerplate with the design library of your choice

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#3]
# Feature Request

### Describe your problem
Set up the project structure with the design library (bulma)

**Comment by garvitchittora** [comment]
@Tlazypanda can I do this one?

**Comment by Tlazypanda** [comment]
@garvitchittora yes go ahead 🎉

**Comment by garvitchittora** [comment]
@Tlazypanda please review my PR.
