### ISSUE TITLE
Design project section

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#30]
# Feature Request

### Describe your problem
Design the project section and cards. The project section should have a heading "Project" followed by the list of projects. For now, you may create a single entry. Also don't forget to link the Project section to the navbar Project link.

Make sure that the section makes use of Bulma elements.

**Comment by riyabhatia26** [comment]
Could you please assign it to me?

**Comment by Tlazypanda** [comment]
Hey @riyabhatia26 go ahead 🎉 also looping in @garvitchittora and @stygian-96 to edit the issue description to provide Riya with more information on how to approach this issue. Thanks!

**Comment by stygian-96** [comment]
@riyabhatia26 in projects page make a card using dummy image, project title, project description and project owner details. Use bulma to design cards.
Also don't forget to put the heading 'Projects' in the page and then put the dummy cards.
In case of any problem or difficulty doing things add a comment :)

**Comment by garvitchittora** [comment]
Hey, @riyabhatia26 need any help?

**Comment by garvitchittora** [comment]
@Tlazypanda since @riyabhatia26  is not responding can I work on this?

**Comment by Tlazypanda** [comment]
Yes @garvitchittora go ahead 💯

**Comment by garvitchittora** [comment]
@Tlazypanda this will work?

![Screenshot (358)](https://user-images.githubusercontent.com/54021348/95649309-871f2880-0afa-11eb-95aa-7b0289e56cfc.png)

**Comment by Tlazypanda** [comment]
Hey @garvitchittora the purple color text might be a bit difficult to read 😅

**Comment by garvitchittora** [comment]
@Tlazypanda ok ma'am noted, except that?

**Comment by Tlazypanda** [comment]
Hey @garvitchittora rest all looks good I am assuming the two squares at the bottom are for social links 😅
