### ISSUE TITLE
Add link to "Issue_Resource_Template.md' to readme.md

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#39]
# Feature Request

### Describe your problem
Add a link to "Issue_Resource_Template.md' to readme.md under the heading "Resources to get started".

**Comment by l3g3ndf4i541** [comment]
Can I work on this? Please assign.

**Comment by jcombs0929** [comment]
I'd like to help if issue is still available.

**Comment by Tlazypanda** [comment]
Hey @l3g3ndf4i541 you have opened the pr in your fork instead of the main repository 😅

**Comment by Tlazypanda** [comment]
Hey @jcombs0929 can I suggest working on #40  since it's for everyone?

**Comment by l3g3ndf4i541** [comment]
@Tlazypanda My bad, just a beginner. Corrected it, but maybe it's too late. Could you not merge and just add hacktoberfest label for it to count? since it's changed to readme from another issue.

**Comment by Tlazypanda** [comment]
Closed via #85
