### ISSUE TITLE
Add contact us section Part (1/2)

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#44]
# Feature Request

### Describe your problem
Add contact us section with a heading "Contact us" followed by a form with the Inputs "Name", "Email", "Message".  The form doesn't need to be functional right now and will be taken up in the next part. 

Please make sure that you use Bulma elements and classes for this.

**Comment by Ayush-Baranwal** [comment]
Can I contribute to this ?

**Comment by Priyansh-09** [comment]
@Tlazypanda I would like to contribute on this

**Comment by Tlazypanda** [comment]
Hey @Ayush-Baranwal go ahead 🎉

**Comment by Junior-Adadie** [comment]
Hey, I would like to contribute on this

**Comment by c99SRS** [comment]
Hi @Tlazypanda , Is this still available to work on?

**Comment by crazy548** [comment]
i would like to work on this.

**Comment by geeks5551** [comment]
Can i work on this @Tlazypanda ?

**Comment by Tlazypanda** [comment]
Closed via #78
