### ISSUE TITLE
Add contact us section Part (2/2) 

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#45]
# Feature Request

### Describe your problem
This issue addresses making the Form functional and adding a script for allowing the form submit button to send the details of the form as an email to a recipient.

**Comment by stygian-96** [comment]
Can I work on this ?

**Comment by Priyansh-09** [comment]
@Tlazypanda Can I work on this issue ?

**Comment by Tlazypanda** [comment]
Hey @stygian-96 go ahead 🎉 @Priyansh-09 let me find another issue for you

**Comment by kumarmanish03** [comment]
@Tlazypanda Is it still open, if so assign to me please
