### ISSUE TITLE
Team Card icons not visible

### ISSUE THREAD

**Issue by garvitchittora** [Elevate-Lab/elevate-lab-website#52]
# Bug Report 

### Issue Summary

 In team card icons of GitHub, LinkedIn and Twitter are not visible fix this bug 🐛  .

![Screenshot (351)](https://user-images.githubusercontent.com/54021348/95595012-517e2f00-0a69-11eb-965c-a56ba585916c.png)

### Expected Behavior

![Screenshot (352)](https://user-images.githubusercontent.com/54021348/95595368-b46fc600-0a69-11eb-9b44-7b329d78de6c.png)
 

### Steps 

1. Check team.html :wink:.

**Comment by sandy9808** [comment]
Can i ?😄

**Comment by garvitchittora** [comment]
Hey @sandy9808 go ahead 🎉
