### ISSUE TITLE
Add "license" badge to readme

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#70]
# Feature Request

### Describe your problem
Add the license as a badge to readme.

**Comment by syauqy** [comment]
Can I work on this?
What kind of license do you want? Creative commons? MIT?

**Comment by Tlazypanda** [comment]
Hey @syauqy Go ahead :tada: we are using the MIT license https://github.com/Elevate-Lab/elevate-lab-website/blob/main/LICENSE

**Comment by Tlazypanda** [comment]
Closed via #75
