### ISSUE TITLE
Change Issue_Resource_Template.txt file to markdown

### ISSUE THREAD

**Issue by Tlazypanda** [Elevate-Lab/elevate-lab-website#72]
# Feature Request

### Describe your problem
Currently the issue_resourcd_template is a text file, update it into markdown file or in a .md format.

**Comment by Sumit-Sahu** [comment]
Can I work on this? Please assign.

**Comment by Tlazypanda** [comment]
Hey @Sumit-Sahu go ahead :tada:

**Comment by Jyotika999** [comment]
@Tlazypanda Mam , Can i work on it?

**Comment by Sumit-Sahu** [comment]
> @Tlazypanda Mam , Can i work on it?

I was working on it. btw  you make pr.

**Comment by Tlazypanda** [comment]
Hey @Sumit-Sahu please go ahead and make the pr 😅 @Jyotika999 let me try to find another issue for you since it was already assigned. Thank you both! ✌️

**Comment by Sumit-Sahu** [comment]
#96
