### ISSUE TITLE
NavBar: Hover Effect changes background color of inactive items 

### ISSUE THREAD

**Issue by deepakDOTexe** [Elevate-Lab/elevate-lab-website#87]
# Bug Report 

### Issue Summary

For the inactive navbar menu items, the background color changes after clicking the item.

### Expected Behavior

 
After clicking on an inactive item and hovering over another item, the background color of the clicked item should not change, only the text colour should change.

### Observed Behavior

I found that after hovering over other items, the clicked item's background color changes to white. This happens only for the inactive navbar items and not the ones which a reference link.

### Steps to Reproduce

1. Clone the repo
2. Run the project in your browser
3. Click on navbar items 

### Screenshots (if any)

![bug1](https://user-images.githubusercontent.com/46655706/95658024-74761500-0b35-11eb-8236-d2765d094434.gif)

**Comment by garvitchittora** [comment]
@deepakDOTexe can I work on this?

**Comment by Priyansh-09** [comment]
Can I work on this ? @deepakDOTexe

**Comment by deepakDOTexe** [comment]
@garvitchittora was the first one to comment so this issue is assigned to him. 
@Priyansh-09 you can look for other issues or check back later and if the issue is not resolved you can work on it.

**Comment by garvitchittora** [comment]
@deepakDOTexe plz merge my PR.
