### ISSUE TITLE
NavBar: Make the navigation bar fixed while scrolling

### ISSUE THREAD

**Issue by tejma17** [Elevate-Lab/elevate-lab-website#88]

**Comment by Priyansh-09** [comment]
@tejma17 can I work on this ?

**Comment by tejma17** [comment]
Sure @Priyansh-09 go ahead.

**Comment by c99SRS** [comment]
Hi @Tlazypanda , is this issue still open?

**Comment by Priyansh-09** [comment]
@tejma17 I have created a pull request #103 to solve issues #88 and #89 . Please review it.

**Comment by Priyansh-09** [comment]
I can fix the issues caused earlier
