### ISSUE TITLE
Add reference links to the Elevate-Lab logo and text

### ISSUE THREAD

**Issue by deepakDOTexe** [Elevate-Lab/elevate-lab-website#89]
# Feature Request

### Describe your problem

After clicking Elevate-Lab Logo or Text, I just stay there. That is there's no reference link.

### Describe the solution you'd like

I would want to navigate back to the landing page when I click the Elevate-Lab Text and to the github organization page when I click on the logo. A better user experience imo.

### Additional context

Many websites have this feature as it is a common user behaviour to click on highlighted texts or logos usually when they are of the organization name or related to it.

**Comment by garvitchittora** [comment]
@deepakDOTexe can I?

**Comment by Priyansh-09** [comment]
@deepakDOTexe can I work on this ??

**Comment by deepakDOTexe** [comment]
@Priyansh-09 go ahead with this one @garvitchittora has already an issue assigned to him.

**Comment by Priyansh-09** [comment]
@Tlazypanda @deepakDOTexe I have created a pull request #103 to solve this issue. Please review it.

**Comment by Priyansh-09** [comment]
I can fix the issue caused earlier
