### ISSUE TITLE
Nav Bar: Not responding on pages other than Home page on Mobile view

### ISSUE THREAD

**Issue by hardikbajaj** [Elevate-Lab/elevate-lab-website#90]
# Bug Report 

### Issue Summary

The NavBar is responding only in the home page, (not responding on teams page)on the mobile view of website. It may create more problems when number of pages will increase.
Also NavBar on home page(mobile view) is also not looking nice.

### Expected Behavior

 
When we click on nav bar icon, it will collapse.

### Observed Behavior

The NavBar didn't responded

### Steps to Reproduce

1.Click on NavBar icon in teams page.

**Comment by Elemento24** [comment]
I would like to work on this Issue. Can I ?

**Comment by deepakDOTexe** [comment]
@Elemento24 yes you can work on this.

**Comment by Elemento24** [comment]
Hey @deepakDOTexe Can you please review the changes. I have fixed the aforementioned bug. Turns out the scripts were commented.
