### ISSUE TITLE
Overlapping cards in Project page on mobile view 

### ISSUE THREAD

**Issue by tejma17** [Elevate-Lab/elevate-lab-website#93]
Fix the alignment of **Project** page on the mobile view.

![issue_mobile_view](https://user-images.githubusercontent.com/61201718/95659002-fe28e100-0b3b-11eb-9b6e-3b6852ed4663.png)

**Comment by garvitchittora** [comment]
@tejma17 can I work on this?

**Comment by tejma17** [comment]
@garvitchittora go ahead

**Comment by garvitchittora** [comment]
@tejma17 plz review my PR.
