### ISSUE TITLE
Navbar:Make It More Responsive

### ISSUE THREAD

**Issue by geeks5551** [Elevate-Lab/elevate-lab-website#99]
make navbar more responsive by adding  animated hovering effect and transitions

**Comment by Priyansh-09** [comment]
This issue is the combination of issue assigned to me (fix navbar scrolling) and issue assigned to @garvitchittora (adding hover effects on navbar items). So this issue that you have opened is conflicting those two issues that was assigned to us before.

**Comment by BLACK-PEARLL** [comment]
i want to work on this :)

**Comment by Tlazypanda** [comment]
Hey @BLACK-PEARLL actually @geeks5551 has already opened an issue for this, I suggest you take up #40 which is open for all :sweat_smile:
